meta_product_name: "Adrien Zafiropoulos"
meta_title: "Adrien Zafiropoulos | Junior Web Developer"
meta_description: "Hello, I am Adrien Zafiropoulos a french full-stack developer. In my website you will find all my projects. Want to work together? Or just drink coffee? Contact me!"
meta_image: "banner_AZ.jpeg"
twitter_account: "@AdrienRules"
